# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

plugins: [jekyll-paginate, rmagick, jekyll-minifier, jekyll-sitemap, jekyll-seo-tag, jekyll-pwa-workbox]
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title:

title: Yohann Streibel
description: Yohann Streibel blog
author:
  name: Yohann Streibel
  email: yohann.streibel@gmail.com
  github: ystreibel
  twitter: ystreibel
  linkedin: ystreibel
  bio: Cloud Engineer @MyScript.<br />JavaScript and HTML5 software developper. 
  email_md5: fc0d8f4187e6eda0ab2d287f27da92a7

rss_path: feed.xml
categories_path: categories.html
about_path: about.html

jekyll-minifier:
  uglifier_args:
    harmony: true

pwa:
  sw_src_filepath: service-worker.js # Optional
  sw_dest_filename: service-worker.js # Optional
  dest_js_directory: assets/js # Required
  precache_recent_posts_num: 5 # Optional
  precache_glob_directory: / # Optional
  precache_glob_patterns: # Optional
    - "{js,css,fonts}/**/*.{js,css,eot,svg,ttf,woff}"
    - index.html
  precache_glob_ignores: # Optional
    - sw-register.js
    - "fonts/**/*"

BASE_PATH:
